# Generated by Django 3.0.8 on 2020-12-30 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='completed',
        ),
        migrations.AddField(
            model_name='item',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='todoapp.User'),
            preserve_default=False,
        ),
    ]
