# Generated by Django 3.0.8 on 2021-01-05 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0006_auto_20210105_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='completed',
        ),
        migrations.AddField(
            model_name='item',
            name='completedField',
            field=models.CharField(default=0, max_length=1),
        ),
    ]
