# Generated by Django 3.0.8 on 2021-01-05 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0007_auto_20210105_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='completedField',
        ),
        migrations.AddField(
            model_name='item',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
